version: "3"
services:
  mysql:
    image: mysql:8
    ports:
      - '8888:3306'
    environment:
      MYSQL_DATABASE: bikes
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost","-uroot","-proot" ]
      interval: 10s
      timeout: 20s
      retries: 3

  web:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /code
    command: >
      sh -c "python manage.py migrate &&
             python manage.py createsuperuser --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DBNAME=bikes
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_HOST=mysql
      - DB_PORT=3306
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=akshaybb.1025@gmail.com
      - DJANGO_SUPERUSER_PASSWORD=admin
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:

